inhibit_all_warnings!

platform :ios, '9.0'

target 'Example' do
	use_frameworks!
	
	pod 'Flamingo', :path => '../'
	pod 'AlamofireImage', '~> 3.1.0'
	pod 'Fakery', '~> 2.0.0'
    pod 'Cache', '~> 2.2.2'
end
