# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flamingo' do
	use_frameworks!

	pod 'Alamofire', '~> 3.4.0'
	pod 'AlamofireImage', '~> 2.4.0'
	pod 'Cache', '~> 1.3.0'
	pod 'ObjectMapper', '~> 1.2.0'
end
